/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.adpl.kedaikopigui.event;

/**
 *
 * @author Lenovo
 */
public class CheckBoxTambahan extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CheckBoxTambahan.class.getName());

    /**
     * Creates new form CheckBoxTambahan
     */
    public CheckBoxTambahan() {
        initComponents();
    }
    
    private String formatRupiah(int nominal) {
        return "Rp" + String.format(java.util.Locale.forLanguageTag("id-ID"), "%,d", nominal);
    }
    
    private void hitungTotal() {
        int total = 22000;
        if(cbGulaAren.isSelected()) total += 3000;
        if(cbSusuOat.isSelected()) total += 5000;
        if(cbExtraShot.isSelected()) total += 4000;
        
        lblHarga.setText(formatRupiah(total));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTambah = new javax.swing.JLabel();
        lblKopi = new javax.swing.JLabel();
        cbGulaAren = new javax.swing.JCheckBox();
        cbSusuOat = new javax.swing.JCheckBox();
        cbExtraShot = new javax.swing.JCheckBox();
        lblTotal = new javax.swing.JLabel();
        lblHarga = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tambahan Kopi");

        lblTambah.setText("Tambahan:");

        lblKopi.setText("Latte - Rp20.000");

        cbGulaAren.setText("Gula Aren (+Rp 3.000)");
        cbGulaAren.addActionListener(this::cbGulaArenActionPerformed);

        cbSusuOat.setText("Susu Oat (+ Rp 5.000}");
        cbSusuOat.addActionListener(this::cbSusuOatActionPerformed);

        cbExtraShot.setText("Extra Shot (+ Rp 4.000)");
        cbExtraShot.addActionListener(this::cbExtraShotActionPerformed);

        lblTotal.setText("Total:");

        lblHarga.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblHarga.setText("Rp 20.000");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTambah)
                    .addComponent(lblKopi)
                    .addComponent(cbGulaAren)
                    .addComponent(cbSusuOat)
                    .addComponent(cbExtraShot)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTotal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblHarga)))
                .addContainerGap(252, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblKopi)
                .addGap(18, 18, 18)
                .addComponent(lblTambah)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbGulaAren)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbSusuOat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbExtraShot)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 134, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotal)
                    .addComponent(lblHarga))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbSusuOatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSusuOatActionPerformed
        // TODO add your handling code here:
        hitungTotal();
    }//GEN-LAST:event_cbSusuOatActionPerformed

    private void cbGulaArenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbGulaArenActionPerformed
        // TODO add your handling code here:
        hitungTotal();
    }//GEN-LAST:event_cbGulaArenActionPerformed

    private void cbExtraShotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbExtraShotActionPerformed
        // TODO add your handling code here:
        hitungTotal();
    }//GEN-LAST:event_cbExtraShotActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CheckBoxTambahan().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cbExtraShot;
    private javax.swing.JCheckBox cbGulaAren;
    private javax.swing.JCheckBox cbSusuOat;
    private javax.swing.JLabel lblHarga;
    private javax.swing.JLabel lblKopi;
    private javax.swing.JLabel lblTambah;
    private javax.swing.JLabel lblTotal;
    // End of variables declaration//GEN-END:variables
}
