/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.adpl.kedaikopigui.layout;

/**
 *
 * @author Lenovo
 */
public class BorderLayoutMenu extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(BorderLayoutMenu.class.getName());

    /**
     * Creates new form BorderLayoutMenu
     */
    public BorderLayoutMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblJudul = new javax.swing.JLabel();
        lblNamaKopi = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ExtDeskripsi = new javax.swing.JTextArea();
        lblHarga = new javax.swing.JLabel();
        lblJamBuka = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Kopi");
        getContentPane().setLayout(new java.awt.BorderLayout(6, 6));

        lblJudul.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblJudul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJudul.setText("Kopi Pilihan Hari Ini");
        getContentPane().add(lblJudul, java.awt.BorderLayout.PAGE_START);

        lblNamaKopi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNamaKopi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNamaKopi.setText("Americano");
        lblNamaKopi.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lblNamaKopi, java.awt.BorderLayout.LINE_START);

        ExtDeskripsi.setEditable(false);
        ExtDeskripsi.setColumns(20);
        ExtDeskripsi.setLineWrap(true);
        ExtDeskripsi.setRows(5);
        ExtDeskripsi.setText("Kopi yang dibuat dari espresso yang dicampur dengan air panas. Rasanya lebih ringan dari espresso, tetapi tetap memiliki cita rasa kopi yang kuat dan khas.");
        ExtDeskripsi.setName(""); // NOI18N
        jScrollPane1.setViewportView(ExtDeskripsi);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        lblHarga.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        lblHarga.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHarga.setText("Rp18.000");
        getContentPane().add(lblHarga, java.awt.BorderLayout.LINE_END);
        lblHarga.getAccessibleContext().setAccessibleName("Rp18.000");

        lblJamBuka.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJamBuka.setText("Buka Setiap Hari 08.00 - 23.00");
        getContentPane().add(lblJamBuka, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new BorderLayoutMenu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea ExtDeskripsi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblHarga;
    private javax.swing.JLabel lblJamBuka;
    private javax.swing.JLabel lblJudul;
    private javax.swing.JLabel lblNamaKopi;
    // End of variables declaration//GEN-END:variables
}
